In [30]:
sent="Nepal contains some of the most rugged and difficult mountain terrain in the world. Roughly 75 percent of the country is covered by mountains. From the south to the north, Nepal can be divided into four main physical belts."

In [31]:
sent

'Nepal contains some of the most rugged and difficult mountain terrain in the world. Roughly 75 percent of the country is covered by mountains. From the south to the north, Nepal can be divided into four main physical belts.'

In [32]:
import nltk

In [33]:
from nltk.tokenize import sent_tokenize


In [34]:
# %pip install nltk

In [35]:
# nltk.download('punkt',download_dir=r'd:\RNN_project\venv\Lib\site-packages\nltk\tokenize')
# # nltk.download('punkt_tab')

In [36]:
sent=sent_tokenize(sent)
sent

['Nepal contains some of the most rugged and difficult mountain terrain in the world.',
 'Roughly 75 percent of the country is covered by mountains.',
 'From the south to the north, Nepal can be divided into four main physical belts.']

In [39]:
x=[word for word in sent]
x

['Nepal contains some of the most rugged and difficult mountain terrain in the world.',
 'Roughly 75 percent of the country is covered by mountains.',
 'From the south to the north, Nepal can be divided into four main physical belts.']

In [38]:
from tensorflow.keras.preprocessing.text import one_hot

In [40]:
#define vocabulary size
voc_size=50
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[40, 15, 38, 19, 43, 31, 36, 37, 30, 21, 33, 16, 43, 45],
 [25, 21, 38, 19, 43, 47, 5, 17, 42, 15],
 [9, 43, 22, 4, 43, 33, 40, 35, 5, 21, 46, 38, 17, 13, 22]]

In [63]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import tensorflow as tf

In [48]:

sent_length=16
pad_sent=pad_sequences(one_hot_repr,padding='post',maxlen=sent_length)
print(pad_sent)

[[40 15 38 19 43 31 36 37 30 21 33 16 43 45  0  0]
 [25 21 38 19 43 47  5 17 42 15  0  0  0  0  0  0]
 [ 9 43 22  4 43 33 40 35  5 21 46 38 17 13 22  0]]


In [64]:
##feature representation
dim = 10
model=Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.add(tf.keras.layers.Flatten())  # Add this line
model.compile(optimizer='adam', loss='mse')
model.build((None, sent_length))  # Add this line
model.summary()




d:\RNN_project\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 16, 10)         │           500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 160)            │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 500 (1.95 KB)

 Trainable params: 500 (1.95 KB)

 Non-trainable params: 0 (0.00 B)